import { registerLocaleData } from '@angular/common';
import pt from '@angular/common/locales/pt';
import { LOCALE_ID } from '@angular/core';
import { provideHttpClient } from '@angular/common/http';
import { HttpTestingController, provideHttpClientTesting } from '@angular/common/http/testing';
import { TestBed } from '@angular/core/testing';
import { provideRouter } from '@angular/router';
import { Sessao } from '../core/sessao';
import { CarteiraPage } from './carteira';
import { OperacoesPage } from './operacoes';

registerLocaleData(pt);
describe('Seleção de ativos e corretoras',()=>{let http:HttpTestingController;const base='http://localhost:8080/api';const xp={id:1,codigo:'XP',nome:'XP Investimentos',ativa:true,legada:false, cnpj: '19131243000197', mercado: 'BR' as const, verificadoEm: '2026-09-06T12:00:00Z'};const inter={id:2,codigo:'INTER',nome:'Inter DTVM',ativa:true,legada:false, cnpj: '19131243000197', mercado: 'BR' as const, verificadoEm: '2026-09-06T12:00:00Z'};const legado={id:3,codigo:'NAO_INFORMADA',nome:'Corretora não informada',ativa:false,legada:true, cnpj: null, mercado: 'BR' as const, verificadoEm: null};const posicoes=[{simbolo:'PETR4',corretora:xp,quantidade:5,precoMedio:20,custoTotal:100,moeda:'BRL'},{simbolo:'PETR4',corretora:inter,quantidade:10,precoMedio:40,custoTotal:400,moeda:'BRL'}];
 beforeEach(()=>{TestBed.configureTestingModule({providers:[provideHttpClient(),provideHttpClientTesting(),provideRouter([]),{provide:LOCALE_ID,useValue:'pt-BR'}]});http=TestBed.inject(HttpTestingController);const s=TestBed.inject(Sessao);s.definirToken('token-teste');s.identificar({id:1,nome:'Teste',email:'teste@example.invalid'});});afterEach(()=>http.verify());
 function operacoes(){const fixture=TestBed.createComponent(OperacoesPage);fixture.detectChanges();http.expectOne(base+'/transacoes').flush([]);http.expectOne(base+'/corretoras').flush([legado,inter,xp]);http.expectOne(base+'/carteira/corretoras').flush(posicoes);return fixture;}
 it('busca explicitamente e invalida a seleção quando o texto muda',async()=>{const fixture=operacoes(),page=fixture.componentInstance;page.alterarBusca('petr');expect(page.form.controls.simbolo.value).toBe('');page.buscarAtivos();const req=http.expectOne(base+'/ativos?busca=PETR&pagina=0&tamanho=20');expect(req.request.headers.get('Authorization')).toBe('Bearer token-teste');req.flush({itens:[{simbolo:'PETR4'}],pagina:0,tamanho:20,total:1,atualizadoEm:'2026-09-06T12:00:00Z',desatualizado:false});page.selecionarAtivo('PETR4');expect(page.form.controls.simbolo.value).toBe('PETR4');http.expectOne(base+'/cotacoes/PETR4').flush({simbolo:'PETR4',nome:'Petrobras',bolsa:'B3',preco:20.5,fonte:'BRAPI',moeda:'BRL'});expect(page.form.controls.valorUnitario.value).toBe('20,5');page.alterarBusca('vale');expect(page.form.controls.simbolo.value).toBe('');expect(page.form.controls.valorUnitario.value).toBe('');});
 it('mantém busca e seletores em controles nativos acessíveis por teclado',()=>{const fixture=operacoes();fixture.detectChanges();const raiz=fixture.nativeElement as HTMLElement;const busca=raiz.querySelector<HTMLInputElement>('#busca-ativo')!;const botao=raiz.querySelector<HTMLButtonElement>('.asset-search button')!;const ativo=raiz.querySelector<HTMLSelectElement>('#simbolo-operacao')!;const corretora=raiz.querySelector<HTMLSelectElement>('#corretora-operacao')!;expect(busca.tagName).toBe('INPUT');expect(botao.tagName).toBe('BUTTON');expect(botao.type).toBe('button');expect(ativo.tagName).toBe('SELECT');expect(corretora.tagName).toBe('SELECT');busca.focus();expect(document.activeElement).toBe(busca);botao.focus();expect(document.activeElement).toBe(botao);ativo.focus();expect(document.activeElement).toBe(ativo);corretora.focus();expect(document.activeElement).toBe(corretora);});
 it('oferece somente corretoras ativas para compra e restringe venda ao saldo do ativo',()=>{const page=operacoes().componentInstance;page.form.controls.simbolo.setValue('PETR4');expect(page.corretorasPermitidas().map(c=>c.codigo)).toEqual(['INTER','XP']);page.form.controls.tipo.setValue('VENDA');expect(page.corretorasPermitidas().map(c=>c.codigo)).toEqual(['INTER','XP']);page.form.controls.simbolo.setValue('VALE3');expect(page.corretorasPermitidas()).toEqual([]);});
 it('separa saldos de venda por mercado sem restringir corretoras de compra',()=>{const page=operacoes().componentInstance;page.posicoesProprias.update(p=>[...p,{simbolo:'AAPL',corretora:xp,quantidade:2,precoMedio:200,custoTotal:400,moeda:'USD'}]);page.form.controls.tipo.setValue('VENDA');page.form.controls.mercado.setValue('USA');expect(page.ativosProprios()).toEqual(['AAPL']);page.form.controls.simbolo.setValue('AAPL');expect(page.corretorasPermitidas().map(c=>c.codigo)).toEqual(['XP']);page.form.controls.mercado.setValue('BR');expect(page.corretorasPermitidas()).toEqual([]);});
 it('mantém ativos próprios como alternativa quando o catálogo falha',async()=>{const fixture=operacoes(),page=fixture.componentInstance;page.alterarBusca('petr');page.buscarAtivos();http.expectOne(base+'/ativos?busca=PETR&pagina=0&tamanho=20').flush({}, {status:503,statusText:'Unavailable'});fixture.detectChanges();expect(page.ativosProprios()).toEqual(['PETR4']);expect(fixture.nativeElement.textContent).toContain('catálogo está indisponível');expect(fixture.nativeElement.textContent).toContain('PETR4');});
 it('renderiza posições consolidadas e só consulta preço após clique',async()=>{const fixture=TestBed.createComponent(CarteiraPage);fixture.detectChanges();http.expectOne(base+'/carteira').flush([{simbolo:'PETR4',quantidade:15,precoMedio:30,custoTotal:450,moeda:'BRL'}]);http.expectOne(base+'/transacoes').flush([]);await fixture.whenStable();fixture.detectChanges();const titulos=[...fixture.nativeElement.querySelectorAll('.positions-table thead th')].map((e:any)=>e.textContent.trim());expect(titulos).toEqual(['Ação','Quantidade atual','Preço médio','Custo total','Cotação atual','Valor atual']);expect(fixture.nativeElement.querySelectorAll('.positions-table tbody tr').length).toBe(1);http.expectNone(base+'/carteira/avaliacao');fixture.componentInstance.atualizarCotacoes();http.expectOne(base+'/carteira/avaliacao').flush([{simbolo:'PETR4',quantidade:15,precoMedio:30,cotacaoAtual:35,fonte:'BRAPI',custoTotal:450,valorAtual:525,lucroPrejuizo:75,lucroPrejuizoPercentual:16.67,moeda:'BRL'}]);fixture.detectChanges();expect(fixture.nativeElement.textContent).toContain('BRL 35,00');expect(fixture.nativeElement.textContent).toContain('BRL 525,00');});
 it('limpa cotações antigas em nova tentativa com erro sem remover posições',()=>{const page=TestBed.createComponent(CarteiraPage).componentInstance;page.posicoes.set(posicoes);page.cotacoes.set(new Map([['PETR4',{simbolo:'PETR4',quantidade:15,precoMedio:30,cotacaoAtual:35,fonte:'BRAPI',custoTotal:450,valorAtual:525,lucroPrejuizo:75,lucroPrejuizoPercentual:16.67}]]));page.atualizarCotacoes();expect(page.cotacoes().size).toBe(0);http.expectOne(base+'/carteira/avaliacao').flush({}, {status:503,statusText:'Unavailable'});expect(page.posicoes()).toHaveLength(2);expect(page.erroCotacoes()).not.toBe('');});
});
