package com.curso.services;
import com.curso.cotacao.BrapiCatalogoClient;import com.curso.services.exceptions.CatalogoIndisponivelException;import java.time.*;import java.util.*;import org.junit.jupiter.api.*;import static org.junit.jupiter.api.Assertions.*;import static org.mockito.Mockito.*;
class CatalogoAtivosServiceTest{private final BrapiCatalogoClient client=mock(BrapiCatalogoClient.class);private final MutableClock clock=new MutableClock(Instant.parse("2026-09-06T12:00:00Z"));private CatalogoAtivosService service;
 @BeforeEach void init(){reset(client);service=new CatalogoAtivosService(client,clock);}
 @Test void normalizaFiltraOrdenaDeduplicaEPagina(){when(client.buscar()).thenReturn(List.of(" vale3 ","PETR4","petr4","^BVSP","AB-1","ABC","ABCDEFGH12345"));var p=service.listar(" pe ",0,20);assertEquals(List.of("PETR4"),p.itens().stream().map(i->i.simbolo()).toList());assertFalse(p.desatualizado());verify(client).buscar();}
 @Test void cacheDuraSeisHorasESinalizaCopiaVencidaNaFalha(){when(client.buscar()).thenReturn(List.of("PETR4"));service.listar("",0,20);clock.avancar(Duration.ofHours(5));service.listar("",0,20);verify(client,times(1)).buscar();clock.avancar(Duration.ofHours(2));when(client.buscar()).thenThrow(new RuntimeException("segredo externo"));var stale=service.listar("",0,20);assertTrue(stale.desatualizado());assertEquals(Instant.parse("2026-09-06T12:00:00Z"),stale.atualizadoEm());service.listar("",0,20);verify(client,times(2)).buscar();}
 @Test void semCacheFalha503LogicaERespeitaBackoff(){when(client.buscar()).thenThrow(new RuntimeException());assertThrows(CatalogoIndisponivelException.class,()->service.listar("",0,20));assertThrows(CatalogoIndisponivelException.class,()->service.listar("",0,20));verify(client,times(1)).buscar();}
 @Test void duasBuscasConcorrentesFazemUmaAtualizacao()throws Exception{var entrou=new java.util.concurrent.CountDownLatch(1);var liberar=new java.util.concurrent.CountDownLatch(1);when(client.buscar()).thenAnswer(i->{entrou.countDown();liberar.await(10,java.util.concurrent.TimeUnit.SECONDS);return List.of("PETR4");});var pool=java.util.concurrent.Executors.newFixedThreadPool(2);try{var a=pool.submit(()->service.listar("PETR",0,20));assertTrue(entrou.await(10,java.util.concurrent.TimeUnit.SECONDS));var b=pool.submit(()->service.listar("PETR",0,20));liberar.countDown();assertEquals(1,a.get(10,java.util.concurrent.TimeUnit.SECONDS).total());assertEquals(1,b.get(10,java.util.concurrent.TimeUnit.SECONDS).total());verify(client,times(1)).buscar();}finally{liberar.countDown();pool.shutdownNow();}}
 @Test void validaPaginacaoEBusca(){assertThrows(IllegalArgumentException.class,()->service.listar("PETR/4",0,20));assertThrows(IllegalArgumentException.class,()->service.listar("",-1,20));assertThrows(IllegalArgumentException.class,()->service.listar("",0,101));verifyNoInteractions(client);}
 @Test void paginaSemItensEValidaEConservaOTotal(){when(client.buscar()).thenReturn(List.of("ABCD4","EFGH4","IJKL4"));var p=service.listar("",1,2);assertEquals(List.of("IJKL4"),p.itens().stream().map(i->i.simbolo()).toList());assertEquals(3,p.total());assertTrue(service.listar("",3,2).itens().isEmpty());verify(client,times(1)).buscar();}
 static final class MutableClock extends Clock{private Instant agora;MutableClock(Instant i){agora=i;}void avancar(Duration d){agora=agora.plus(d);}public ZoneId getZone(){return ZoneOffset.UTC;}public Clock withZone(ZoneId z){return this;}public Instant instant(){return agora;}}
}
