package com.curso.services;
import com.curso.cotacao.*;import com.curso.domains.*;import com.curso.domains.dtos.InvestimentoDTOs.TransacaoRequest;import com.curso.domains.enums.*;import com.curso.repositories.*;import com.curso.services.exceptions.RegraNegocioException;import java.math.BigDecimal;import java.time.LocalDateTime;import java.util.*;import org.junit.jupiter.api.*;import static org.junit.jupiter.api.Assertions.*;import static org.mockito.Mockito.*;
class PosicaoPorCorretoraTest{private final TransacaoRepository repo=mock(TransacaoRepository.class);private final AtivoRepository ativos=mock(AtivoRepository.class);private final UsuarioAtualService atual=mock(UsuarioAtualService.class);private final CotacaoOrchestrator orq=mock(CotacaoOrchestrator.class);private final CorretoraService cs=mock(CorretoraService.class);private final Usuario u=new Usuario(1L,"U","u@test.com","1","h");private final Ativo ativo=new Ativo(2L,"PETR4","Petrobras","B3");private final Corretora a=new Corretora(1L,"XP","XP Investimentos",true,false),b=new Corretora(2L,"INTER","Inter DTVM",true,false);private final LocalDateTime d=LocalDateTime.of(2026,9,1,10,0);private final TransacaoService service=new TransacaoService(repo,ativos,atual,new CalculadoraPosicao(),orq,cs,java.time.Clock.systemUTC());
 private Transacao t(long id,Corretora c,TipoTransacao tipo,String q,String v,int hora){return new Transacao(id,u,ativo,c,tipo,new BigDecimal(q),new BigDecimal(v),d.plusHours(hora));}
 @BeforeEach void init(){when(atual.obter()).thenReturn(u);when(atual.bloquear()).thenReturn(u);when(ativos.findBySimboloIgnoreCase("PETR4")).thenReturn(Optional.of(ativo));when(repo.save(any())).thenAnswer(i->i.getArgument(0));when(cs.obterParaOperacao(2L,TipoTransacao.VENDA)).thenReturn(b);}
 @Test void calculaCustosLocaisEConsolidadoConformeCenarioAprovado(){var itens=List.of(t(1,a,TipoTransacao.COMPRA,"10","20",0),t(2,b,TipoTransacao.COMPRA,"10","40",1),t(3,a,TipoTransacao.VENDA,"5","50",2));when(repo.findByUsuarioIdOrderByDataOperacaoAscIdAsc(1L)).thenReturn(itens);var locais=service.posicoesPorCorretora();assertEquals(2,locais.size());assertEquals(new BigDecimal("400.00"),locais.get(0).custoTotal());assertEquals(new BigDecimal("100.00"),locais.get(1).custoTotal());var global=service.posicoes().get(0);assertEquals(new BigDecimal("15.000000"),global.quantidade());assertEquals(new BigDecimal("30.000000"),global.precoMedio());assertEquals(new BigDecimal("450.00"),global.custoTotal());verifyNoInteractions(orq);}
 @Test void naoPermiteVenderSaldoMantidoEmOutraCorretora(){when(repo.findForUpdate(1L,2L)).thenReturn(List.of(t(1,a,TipoTransacao.COMPRA,"10","20",0)));assertThrows(RegraNegocioException.class,()->service.registrar(new TransacaoRequest("PETR4",2L,TipoTransacao.VENDA,new BigDecimal("1"),new BigDecimal("30"),d.plusHours(1))));verify(repo,never()).save(any());}
 @Test void permiteVenderSaldoLegadoSomenteComCategoriaExplicitamenteSelecionada(){var legado=new Corretora(3L,"NAO_INFORMADA","Corretora não informada",false,true);when(cs.obterParaOperacao(3L,TipoTransacao.VENDA)).thenReturn(legado);when(repo.findForUpdate(1L,2L)).thenReturn(List.of(t(1,legado,TipoTransacao.COMPRA,"2","20",0)));assertEquals(TipoTransacao.VENDA,service.registrar(new TransacaoRequest("PETR4",3L,TipoTransacao.VENDA,new BigDecimal("1"),new BigDecimal("21"),d.plusHours(1))).tipo());verify(repo).save(any());}
 @Test void avaliacaoConsultaUmaVezMesmoComDuasCorretoras(){when(repo.findByUsuarioIdOrderByDataOperacaoAscIdAsc(1L)).thenReturn(List.of(t(1,a,TipoTransacao.COMPRA,"1","20",0),t(2,b,TipoTransacao.COMPRA,"1","40",1)));when(orq.buscar("PETR4")).thenReturn(new CotacaoAtual("PETR4","Petrobras","B3",new BigDecimal("35"),FonteCotacao.BRAPI));assertEquals(1,service.avaliar().size());verify(orq,times(1)).buscar("PETR4");}
}
