package com.curso.cotacao;
import com.curso.config.CotacaoProperties;import com.curso.domains.enums.FonteCotacao;import org.junit.jupiter.api.*;import org.springframework.http.*;import org.springframework.test.web.client.MockRestServiceServer;import org.springframework.web.client.RestClient;import static org.junit.jupiter.api.Assertions.*;import static org.springframework.test.web.client.match.MockRestRequestMatchers.*;import static org.springframework.test.web.client.response.MockRestResponseCreators.*;
class ProvidersTest{private RestClient.Builder builder;private MockRestServiceServer server;private CotacaoProperties props;
 @BeforeEach void init(){builder=RestClient.builder();server=MockRestServiceServer.bindTo(builder).build();var f=new CotacaoProperties.Fonte("http://quotes.test","fake");props=new CotacaoProperties(f,f,f);}
 @Test void brapiExtraiPrimeiroDataEEnviaBearer(){server.expect(requestTo("http://quotes.test/api/v2/stocks/quote?symbols=PETR4")).andExpect(header("Authorization","Bearer fake")).andRespond(withSuccess("{\"results\":[{\"symbol\":\"PETR4\",\"data\":{\"shortName\":\"Petrobras\",\"regularMarketPrice\":31.25}}]}",MediaType.APPLICATION_JSON));var c=new BrapiProvider(builder,props).buscar("PETR4");assertEquals(FonteCotacao.BRAPI,c.fonte());assertEquals(0,c.preco().compareTo(new java.math.BigDecimal("31.25")));server.verify();}
 @Test void brapiRejeitaSimboloDivergente(){server.expect(anything()).andRespond(withSuccess("{\"results\":[{\"symbol\":\"VALE3\",\"data\":{\"regularMarketPrice\":31.25}}]}",MediaType.APPLICATION_JSON));assertThrows(ProviderCotacaoException.class,()->new BrapiProvider(builder,props).buscar("PETR4"));}
 @Test void brapiRejeitaCotacaoSemIdentidade(){server.expect(anything()).andRespond(withSuccess("{\"results\":[{\"data\":{\"regularMarketPrice\":31.25}}]}",MediaType.APPLICATION_JSON));assertThrows(ProviderCotacaoException.class,()->new BrapiProvider(builder,props).buscar("PETR4"));}
 @Test void alphaMapeiaFormatoEspecifico(){server.expect(requestTo("http://quotes.test/query?function=SYMBOL_SEARCH&keywords=PETR4&apikey=fake")).andRespond(withSuccess("{\"bestMatches\":[{\"1. symbol\":\"PETR4.SAO\",\"2. name\":\"Petrobras\",\"8. currency\":\"BRL\"}]}",MediaType.APPLICATION_JSON));server.expect(requestTo("http://quotes.test/query?function=GLOBAL_QUOTE&symbol=PETR4.SAO&apikey=fake")).andRespond(withSuccess("{\"Global Quote\":{\"05. price\":\"30.10\"}}",MediaType.APPLICATION_JSON));assertEquals(FonteCotacao.ALPHA_VANTAGE,new AlphaVantageProvider(builder,props).buscar("PETR4").fonte());}
 @Test void hgMapeiaFormatoEspecifico(){server.expect(requestTo("http://quotes.test/finance/stock_price?key=fake&symbol=PETR4")).andRespond(withSuccess("{\"results\":{\"PETR4\":{\"symbol\":\"PETR4\",\"name\":\"Petrobras\",\"price\":29.90}}}",MediaType.APPLICATION_JSON));assertEquals(FonteCotacao.HG_FINANCE,new HgFinanceProvider(builder,props).buscar("PETR4").fonte());}
 @Test void brapiVaziaGeraFalhaSegura(){server.expect(anything()).andRespond(withSuccess("{\"results\":[]}",MediaType.APPLICATION_JSON));var ex=assertThrows(ProviderCotacaoException.class,()->new BrapiProvider(builder,props).buscar("PETR4"));assertFalse(ex.getMessage().contains("fake"));}
 @Test void catalogoBrapiUsaContratoTipado(){server.expect(requestTo("http://quotes.test/api/available")).andRespond(withSuccess("{\"stocks\":[\"PETR4\"],\"indexes\":[\"^BVSP\"]}",MediaType.APPLICATION_JSON));assertEquals(java.util.List.of("PETR4"),new BrapiCatalogoClient(builder,props).buscar());server.verify();}
 @Test void catalogoBrapiRejeitaRespostaSemStocks(){server.expect(anything()).andRespond(withSuccess("{}",MediaType.APPLICATION_JSON));assertThrows(org.springframework.web.client.RestClientException.class,()->new BrapiCatalogoClient(builder,props).buscar());}}
